learningpro/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name="basic_app"

urlpatterns=[
    path("register/",views.register,name="register"),
    path("user_login/",views.user_login,name="user_login"),
    
]

learningpro/learningpro/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path("",views.index,name="index"),
    path('admin/', admin.site.urls),
    path("basic_app/",include("basic_app.urls")),
    path("logout/",views.user_logout,name="logout"),
    path ("special/",views.special,name="special"),
]

learningpro/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio=models.URLField(blank=True)
    picture=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learningpro/basic_app/forms.py
from django import forms
from basic_app.models import UserProfileInfo
from django.contrib.auth.models import User

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=("portfolio","picture")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=("username","email","password")
        

learningpro/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate

# Create your views here.
def index(request):
    return render(request,"basic_app/index.html")

def register(request):
    registered=False

    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(request.POST,request.FILES)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if "picture" in request.FILES:
                profile.picture=request.FILES["picture"]
            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,"basic_app/registration.html",{"user_form":user_form,"profile_form":profile_form,"registered":registered})


def user_login(request):
    if request.method=="POST":

        username=request.POST.get("username")
        password=request.POST.get("password")

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("account is bocked")
        else:
            print("someone tried to login & failed")
            print("username:{} and password :{}".format(username,password))
            return HttpResponse("invalid login details")
    else:
        return render(request,"basic_app/login.html",{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

@login_required
def special(request):
    return HttpResponse("you are loggedin welcome!")

learningpro/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet"  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{%url 'index' %}">Django</a></li>
          <li><a class="navbar-link" href="{%url 'admin:index'%}">admin</a></li>
          <li><a class="navbar-link" href="{%url 'basic_app:register'%}">registration</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout'%}">logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{%url 'basic_app:user_login' %}">login</a></li>
          {% endif %}

        </ul>

      </div>


    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html

learningpro/templates/basic_app/index.html
{%extends 'basic_app/base.html' %}
{%block body_block%}
<div class="jumbotron">
  <h1>welcome to level5</h1>

</div>
{% endblock %}

learningpro/templates/basic_app/login.html
{%extends 'basic_app/base.html'%}
{% block body_block%}
<div class="jumbotron">
  <h1>please login</h1>
  <form action="{% url 'basic_app:user_login' %}" method="POST">
    {% csrf_token%}
    <label for="username">username:</label>
    <input type="text" name="username" placeholder="enter ur name">

    <label for="password">password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="login">
  </form>
</div>
{% endblock %}

learningpro/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>thank you for registering</h1>
  {%else%}
    <h1>register here</h1>
    <h1>fill out the form</h1>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" name="" value="Register">
      <a href="basic_app/thank.html">register</a>

    </form>
  {%endif%}
</div>
{% endblock %}

learningpro/templates/basic_app/thank.html
{%extends "basic_app/base.html"%}
{%block body_block%}
  <h1>thankyou for registering!</h1>
{% endblock %}